name = "CodeSource"
uuid = "9ac50e29-f585-44c0-a7d5-1443d3f96000"
authors = [
    "Jerry Ling <proton@jling.dev>, Ajinkya Kokandakar <ajinkyakokandakar@gmail.com> and contributors",
]
version = "0.1.0"

[deps]
CodeTracking = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"

[compat]
CodeTracking = "1.3.9"
Crayons = "4.1.1"
InteractiveUtils = "1.11.0"
JuliaSyntax = "1.0.2"
OhMyREPL = "0.5.31"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
